### ISSUE TITLE
Reading generated file by ReqEdit Client of REQTEAM

### ISSUE THREAD

**Issue by sssuslov** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#1]
Hallo Sir, 
I used ReqEdit Client (readonly mode) to validate the files, generated by your add-inn for ReqIF exporting.
The SW rejected opening them all due to
"Fatal (SCHEMA): Error: The value of the 'http://www.omg.org/spec/ReqIF/20110401/reqif.xsd:REQ-IF-VERSION' element does not equal its fixed value.; Line and position: 9, 28"
Regards,
Sergey

**Comment by Helmut-Ortmann** [comment]
Hello Sergey,

Thanks for sending me the issue!

I generate the ReqIF with REHAGROUP reqifsharp library (https://github.com/RHEAGROUP/reqifsharp). Then I checked it with tools like DOORS and ReqIF Studio (https://formalmind.com/tools/studio/). You may check your ReqIF file with ReqIF Studio or Eclipse ProR (both free).

If you send me the file and/or the EA model I can look into the issue. I've just seen that ReqEdit is free in the readonly mode. I'll look into the issue and look if I can reproduce it. 

Best regards,

Helmut

**Comment by Helmut-Ortmann** [comment]
Hello Sergey,

could you send me the part of the *.xml file around the specified error (9, 28)? 

Thanks,

Helmut

**Comment by sssuslov** [comment]
Hallo Helmut,
thank you for the rapid reply. I didn't do anything more then just export your exapmle project .eaxp to the .reqif file. Unfortunately, I have not yet find out how to make an uncompressed xml with your tool. The generated reqif file follows in the e-mail as the Comment form does not accept the *reqif format as an attachment (actually the tool cannot read most of the reqif(z) files in your repo exaplmes in you ./Resources dir

). The export configuration is also a straightforward from your tutorial (although I tried several combinations):
      {
               "Name"            :  "02. My ReqIF Export specification",
               "Description"     :  "My ReqIF Export specification",
               "ListNo"          :  "2",
               "ExportFile"       :  "c:/Temp/ReqIF/exportIF.reqif" ,
               "PackageGuidList" :  ["{B408F6F3-A1F9-47f7-8AD4-CBE2284627D1}"],
               "ObjectType"      :  "Requirement",
               "Stereotype"      :  "",
               "StereotypeDependency": "satisfy",
               "ImportType"      :  "ReqIF",
               "StatusNew"       :  "Proposed",
               "EmbeddedFileStorageDictionary" : "c:/Temp/ReqIF/Store/02/"
         },

**Comment by sssuslov** [comment]
update: sorry, I cannot send the attachment to the e-mail address to github, as it is noreply address, and cannot attach the file here as the extension is not allowed for attachments, but I repeat, I simply exported the example project from the repo from EA 14.1, .net 7.4.03

**Comment by sssuslov** [comment]
extension changed from reqif to log (as xml is also not allowed to be attached).
the line #9 contains
<REQ-IF-VERSION>1.2</REQ-IF-VERSION>
do not know, what can be wrong with it
[exportIF.log](https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoReverse/files/2851745/exportIF.log)

**Comment by Helmut-Ortmann** [comment]
Hello Sergey,

thanks for analyzing. It looks that the ReqIF Version 1.2 is somehow wrong. Version 1.0 works. 

The *.reqifz format is in effect a *.zip compression. I use Totalcmd and handling such compressed files is easy. Depending on your compression tool you may change the extension to *.zip.

I'll release a new version.

Best regards,

Helmut

**Comment by Helmut-Ortmann** [comment]
Hello Sergey,

I fixed the issue. You find the new version 3.2.3 as usual under Releases. You can validate and get infos about ReqIF files and folders. See: https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoReverse/wiki/ReqIF_Info

Good luck,

Helmut

**Comment by Helmut-Ortmann** [comment]
Hello Sergey,

I close the issue. Feel free to reopen it if the issue still exists. The newest release is 3.2.4.

Good luck and thanks for your contribution,

Helmut
