### ISSUE TITLE
Export/Import Roundtrip

### ISSUE THREAD

**Issue by aranvir** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#10]
Hallo Helmut,

erstmal vielen Dank für das tolle Tool! Leider habe ich noch ein paar Probleme es bei mir vollständig ans laufen zu kriegen und wollte nach ein paar Tipps fragen.
### Export
Wie kriege ich es hin, dass EA Element Notes exportiert werden? Linked Documents, Tagged Values, und sonstige Informationen werden korrekt übertragen, aber die Element Notes verschwinden leider. Hier mein Export code:
```
    {
          "Name"            :  "Minimal Export",
          "Description"     :  "My ReqIF Export specification",
          "ListNo"          :  "5",
          "ExportFile"       : "c:/Temp/ReqIF/export.reqifz" ,
          "PackageGuidList" :  ["{40A476E8-B4F2-4d1c-9B5A-F7D0A4E092C8}"]
    }
```
Ich habe auch probiert `AttrNotes` mit einzubinden aber das hat leider auch nicht geholfen, deswegen habe ichs bei meinen minimalistischen settings belassen.

### Import
Dann habe ich versucht mein kleines, vormals exportiertes Beispielmodell in eine neue EA file zu importieren (daher auch andere package ID). Leider kriege ich dabei Exceptions mit denen ich nichts anfangen kann.
Zuerst das hier:
![Exception 1](https://user-images.githubusercontent.com/75439739/101055910-b26a4500-358a-11eb-8283-369e5f555ce8.PNG)
Und danach das:
![Exception 2](https://user-images.githubusercontent.com/75439739/101055948-bc8c4380-358a-11eb-8679-3e3f10995ef2.PNG)

Mein import code lautet wie folgt:
``` 
    {
          "Name"            :  "Minimal Import",
          "Description"     :  "My ReqIF Export specification",
          "ListNo"          :  "6",
          "InputFile"       :	"C:/temp/ReqIF/export.reqifz",
          "PackageGuidList" :  ["{1848180F-AB6C-4a38-9AAF-150FFB91941D}"],
	      "ImportType"      :  "ReqIF",
	      "ObjectType"      :  "Requirement", 
          "StatusNew"       :  "Proposed",
	      "RtfNameList"     :  ["ReqIF.Text"],
          "AttrNameList"    :  ["ReqIF.ForeignID", "ReqIF.Chaptername", "ReqIF.Text"],
          "AttrNotes"       :  "ReqIF.Text",
          "AliasList"       :  ["ReqIF.ForeignID"]
    }
```
Auch hier habe ich versucht mich an deinen Beispielen zu orientieren aber es klappt einfach nicht.

Habe ich was übersehen?

### Sonstiges
Die Elemente die ich importiere und exportiere wurden mit einer custom MDG definiert. Da der export aber problemlos klappt (abgesehen von Element Notes), gehe ich davon aus, dass das keine Probleme machen sollte. Ich erwähne es nur, falls es doch relevanz haben könnte.

Vielen Dank und viele Grüße,
Jasper

**Comment by Helmut-Ortmann** [comment]
Hallo Jasper,

hast Du das Tutorial für Import/Export von Requirements durchgeführt?
(
https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoReverse/wiki/ReqIF_Export_Tutorial
).

Normalerweise nehme ich das Tutorial und ändere es bis es klappt. Wichtig
ist es die ReqIF Dateien anzuschauen und zu verstehen. Die Attribute und
den Aufbau.

Es sieht so aus als ob die ReqIF Datei keine Attribute "ChapterName",
"Name" enthält.

Zum Testen von ReqIF habe ich ReqIF Studio verwendet (
https://www.formalmind.com/de/tools/studio/). Es sollte auch mit Eclipse
ProR gehen (https://www.eclipse.org/rmf/). Bestimmt gibt es noch weitere
Tools.

Vor mehreren Jahren habe ich es gemacht und weiß auch nicht mehr alles.
Nach einer Einarbeitungszeit liefen die Prozesse für umfangreiche
Requirements, viele Dokumente gut.


Gruß,

Helmut

**Comment by aranvir** [comment]
Hallo Helmut,

ich habe mir das Tutorial nochmal genau angeguckt. Und die Notes werden tatsächlich richtig exportiert: So lange kein linked document vorhanden ist. Das hatte ich in deiner Beschreibung übersehen.

Die Probleme beim Import muss ich mir nochmal genauer angucken.

Viele Grüße,
Jasper

**Comment by Helmut-Ortmann** [comment]
Hallo Jasper,
danke für die Information.

Wenn ich mich richtig erinnere kannst Du Notes + Linked Documents
exportieren. Bin mir aber nicht 100% sicher.

Gruß und schönes Wochenende,

Helmut
