### ISSUE TITLE
How to install

### ISSUE THREAD

**Issue by GrahamRoach** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#11]
Please give instructions on how to install - msi file seems to be missing

Thnaks

**Comment by Helmut-Ortmann** [comment]
Hi Graham,

go to the GitHub release page (it's a bit hidden):

   -
   https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoReverse/releases

Scroll down to assets and run the "hoReverse.3.9.0.msi" file. Everything
should be explained on the release page.

Best regards,

Helmut
<https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoReverse/releases/download/V3.9/hoReverse.3.9.0.msi>
