### ISSUE TITLE
Crash on import of reqif files with 64bit integer datatype 

### ISSUE THREAD

**Issue by cbalster** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#2]
Hi Helmut,
first of all thank you for open sourcing all this work!
When experimenting with hoReverse I noticed a crash with reqif exports that define an integer datatype with a min/max of 64bit. I pinned this down to the reqifsharp library, that assumed integer to always be 32bit. I already opened an issue with them and it was fixed in record time, see https://github.com/RHEAGROUP/reqifsharp/issues/13
Just wanted to make you aware and kindly ask if you could update your dependency and release a new version when possible.
Thanks again!

**Comment by Helmut-Ortmann** [comment]
Hi Christian,

thanks for your engagement!

Yes, my experiences with the reqifsharp library are the same - very quick.

I've updated the reqifsharp library to 2.0.0 and released it in hoReverse
V3.7.0. Hope it works!

Best regards,

Helmut

**Comment by cbalster** [comment]
Thank you!
