### ISSUE TITLE
Getting errors while building the solution - hoReverse plugin [Importing ReqIf file]

### ISSUE THREAD

**Issue by TVNGoutham9515** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#21]
Hello Heltmut Ortmann,

First-Of-All thanks for you as you have shared hoReverse plugin with all. As this plugin is so much helpful for me to import the requirements into EA using ReqIf files.

I have tried to import the project in Visual Studio, but while building the solution i am facing some errors as shown in below screenshots. Can you please guide me how to resolve the error. Actually, I tried to fix it, but it is not resolved yet.

Thank you in Advance.,

**Comment by TVNGoutham9515** [comment]
[Doc1.docx] (https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoReverse/files/13376465/Doc1.docx)

**Comment by Helmut-Ortmann** [comment]
Hello,

this build event registers the AddIn with the help of the script
RegisterHoReverse*.reg for x86 or x64.

You may delete it for the time being and run it manually when you want to
use the plugin in EA. Why you get the error is unknown to me.

Best regards,

Helmut

**Comment by TVNGoutham9515** [comment]
Hi Heltmut Ortmann,

Thanks for your quick response 😊.
After changing platform to x86 for all the projects then it is working.

And now i am facing some more issues:
First, I have build the solution and then generated the msi file. And then I have run the msi file.
1) when I try to open EA, it is throwing some error i.e., "No default settings in 'hoReverseGui.dll.config' found"
-> Even after getting this error, still hoReverse plugin installed in EA.
2) But when I try to import the requirements using "ReqIf" file, again i am getting one more error i.e., "LinqToDB.LinqToDBException DataProvider 'Microsoft.JET.OLEDB.4.0' not found"

I have attached some screenshots in the file. Kindly help me on this.

**Comment by TVNGoutham9515** [comment]
[Uploading Doc2.docx…]()

**Comment by Helmut-Ortmann** [comment]
Hi,

ODBC driver. On:

- https://stackoverflow.com/questions/13811179/where-how-can-i-download-and-install-the-microsoft-jet-oledb-4-0-for-windows-8
you find how to download the driver. It is used for a JET (old access database).

hoReverseGui.dll.config
You find the file in GIT hoReverseRoot. Just copy it to the dlls of the addin. The location should be shown by the About command. (something like: c:\Users\[user]\AppData\Local\Apps\ho\hoReverse\

Good luck,

Helmut
