### ISSUE TITLE
How to activate the License to convert from HTML to RTF .Net conversion

### ISSUE THREAD

**Issue by TVNGoutham9515** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#22]
Hello Helmut,

When I am importing the Requirements into EA using ReqIf file with help of hoReverse plugin I am getting the water mark called "Created by unlicensed version of HTML to RTF .Net 7.4.4.30" in Text document for all the requirements. In order to remove this water mark I have purchased the license. So how to activate the License?

**Note -** I found one line of code in "HtmlToDocx.cs" class to set the license. Is it correct?
I have attached screenshot in below.

[Doc3.docx](https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoReverse/files/13386073/Doc3.docx)

Thank you in Advance,

**Comment by TVNGoutham9515** [comment]
[Doc4.docx](https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoReverse/files/13386695/Doc4.docx)

**Comment by Helmut-Ortmann** [comment]
Hello,

yes, the line:

   - h = new SautinSoft.HtmlToRtf { Serial = "1028....

should be used for the licence number. I admit, it's a long time ago I've
done it.

Best regards and good luck,

Helmut

**Comment by TVNGoutham9515** [comment]
OK 👍. Thank you so much for your prompt response and providing the information very quickly 😊.

**Comment by SautinSoftSupport** [comment]
Hi. 
Or you may activate it using new serial key of HTML to RTF. Net from reg.sautinsoft.com
It's for free.
