### ISSUE TITLE
How to set the Stereotypes in EA for Requirements using ReqIF import?

### ISSUE THREAD

**Issue by TVNGoutham9515** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#23]
Hello Helmut,

Good Day😊!

Sub - Set the stereotypes dynamically by fetching the information from ReqIf.

I want to set the stereotype to the requirements while importing the ReqIf file. But whatever the value i am passing it is considering as a String. Because of this Every requirement is assigning the same Stereotype as mentioned in "Stereotype" property in settings.json file.

Ex - "Stereotype" : "Functional Requirement"

For all the requirements it is assigning the stereotype as "Functional Requirement" as shown in "Document5" file in below attachments.

But I have Stereotype information in my ReqIf file as shown in "Document6" file in below attachments. How to read this information in settings.json file? or is there any specific column name for it?
In this case, I have different different stereotypes information in the ReqIf. Please find the screenshots for your reference in "Document6" file.

Thank you in Advance,

**Comment by TVNGoutham9515** [comment]
I tried with different options but it didnt worked.
Ex - "Stereotype": "ReqIF.specObject"
       "Stereotype": "ReqIF.SpecObjectType"
       "Stereotype": "ReqIF.Type"
       "Stereotype": "ReqIF.ArtifactType"
       "Stereotype": "ReqIF.SpecObjectType"
       "Stereotype": "specObject"
       "Stereotype": "ReqIFSharp.SpecObjectType"

**Comment by TVNGoutham9515** [comment]
Instead of passing "Static" value to the "Stereotype" property in settings.json, I have to pass values from ReqIf file.
For all the requirements I have stereotype information in ReqIf file as shown in "Document6" attachment

**Comment by Helmut-Ortmann** [comment]
Hello,

You want to assign the EA stereotype of a requirement from a ReqIf
requirement property. This means every EA requirement has the same
stereotype as the corresponding ReqIf requirement entry.

I have looked inside the code. Currently, hoReverse supports only static
Stereotypes - sorry.

Best regards,

Helmut
