### ISSUE TITLE
Linked Document content cannot be exported in Word Document

### ISSUE THREAD

**Issue by TVNGoutham9515** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#24]
Hello Helmut,

Good Day😊!
First of all, thank you so much for your quick response in previous issues which I have addressed earlier. It helped a lot for me in my work activities.

I am facing one more problem while exporting the requirements from EA.
### **Case-1**
When I manually create a requirement and assign a linked document to it, and then proceed with the Word Document export, Pictures/Tables/Data which are present in Linked Document **exported successfully**.
### **Case-2**
When I import the requirements with hoReverse plugin, and then when I try to export the requirements, Pictures/Tables/Data which are present in Linked document **not exported**.

PFA for your reference.
**Kindly let me know how to resolve the issue in **Case-2**.**

[Case_1.docx](https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoReverse/files/13839359/Case_1.docx)
[Case_2.docx](https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoReverse/files/13839364/Case_2.docx)

Thank you in Advance for your great support,
TVN Goutham

**Comment by Helmut-Ortmann** [comment]
Hello TVN,

Thanks for reporting the issue with not exporting a picture (also other embedded files).

Procedure to reproduce:
1. Make a linked document with a *.jpg picture in it
2. Assign the linked document of step 1 to a requirement
3. Export with hoReverse the requirements into a new reqif file
4. Import the exported requirements into a new EA package
5. Export the imported requirements into a new reqif file
6. Another import of the in 5 exported reqif file has no *.jpg pictures in it

I have some questions:
1. Is the above description to reproduce the error correct?
2. Is this reproducable with different embedded files (*.jpg, *.png, *.???)
3. Can you share some files (*.json for step 3,5,6/reqIf files for step 3,5,6), EA model of step 3,5,6?
4. Which use cases are working?

Thanks for participating in getting hoReverse better.

Thanks and best regards,

Helmut
