### ISSUE TITLE
hoLinqToSql part of hoTools

### ISSUE THREAD

**Issue by anebenfuehr** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#3]
hoReverse.sln solution references hoLinqToSql project from hoTools
`Project("{FAE04EC0-301F-11D3-BF4B-00C04F79EFBC}") = "hoLinqToSql", "..\EnterpriseArchitect_hoTools\hoLinqToSql\hoLinqToSql.csproj", "{8DF4F058-9E5E-42FF-B9F5-F6B826983E97}"`

So currently it's not possible to build hoReverse without hoTools.

**Comment by Helmut-Ortmann** [comment]
You are right. I think this is the only dependencies.

Best regards,

Helmut
