### ISSUE TITLE
post build fails / points to c:\hoData\...

### ISSUE THREAD

**Issue by anebenfuehr** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#4]
hoReverse build fails with
```
Schweregrad	Code	Beschreibung	Projekt	Datei	Zeile	Unterdrückungszustand
Fehler		Der Befehl "c:\hoData\Development\GitHub\EnterpriseArchitect_hoReverse\hoReverse_Setup\Scripts\RegisterHoReverse.reg /f" wurde mit dem Code 3 beendet.	hoReverseRoot
```
hoReverseRoot post build points to c:\hoData\...

Change to `$(SolutionDir)\hoReverse_Setup\Scripts\RegisterHoReverse.reg /f`
will fix it.

**Comment by Helmut-Ortmann** [comment]
Thanks for analyzing it and suggesting the solution. I'll fix it with the
next release.

Best regards,

Helmut
