### ISSUE TITLE
EA ReqIF export issue with special character

### ISSUE THREAD

**Issue by AndreasW89** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#6]
Hello Helmut,
thanks for sharing your tools. It's nice to learn from your work and experiences.

My issue relates to the ReqIF export function of your EA Addin hoReverse version 3.8.
If the special character "&" is used in EA  inside the Name, Notes or Linked Documents, an error is thrown after executing your ReqIF export function. The .reqifz file is generated with the .reqif inside but it can not be imported to ReqIF Studio. ReqIF Studio throws an error during import as well.
I checked the reqif file and found the text phrases with the special character "&" in clear text, not as xhtml command, which should be "&", I guess ;-) .
Unfortunately, I'm not able to fix it by my self. Therefore it would be really kind if you could analyse and maybe fix that issue.
Thanks in advance.

**Comment by Helmut-Ortmann** [comment]
Hello Andreas,

Thanks a lot for your elaborate analysis.

On the weekend I'll have a look and try to fix it. With your analyse it
shouldn't be too complicated.

Best regards,

Helmut

**Comment by Helmut-Ortmann** [comment]
Should be fixed in 3.9.

**Comment by AndreasW89** [comment]
Thanks
