### ISSUE TITLE
EA Addin hoReverse - Version number

### ISSUE THREAD

**Issue by AndreasW89** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#7]
Hi Helmut,
i found another topic regarding the version number of your Addin hoReverse 3.8. 
If I click on Add-Ins => hoReverse => "About" the release version shows 3.3.2
Best regards
Andreas

**Comment by Helmut-Ortmann** [comment]
I'll fix it in next release

**Comment by Helmut-Ortmann** [comment]
Should be fixed in 3.9.
