### ISSUE TITLE
MySQL.data exception - Problem during ReqIF export from EA MySQL Server Project

### ISSUE THREAD

**Issue by AndreasW89** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#8]
Hallo Helmut,
ich habe mich jetzt intensiver mit deinem Projekt hoReverse beschäftigt, mit besonderem Augenmerk auf den ReqIF Sachen. Erstmal vielen dank für die tolle Arbeit die du gemacht hast und auch hier mit uns teilst. 
Leider bin ich auf ein Problem gestoßen, welches ich nicht richtig verstehe und bis jetzt leider nicht lösen konnte.
Es geht darum einen ReqIF export von einem MySQL Projekt durchzuführen. Hierbei bekomme ich immer einen Fehler, welchen ich aber nicht richtig nachvollziehen kann. In einem lokalen Projekt gibt es keine Probleme.
Anbei ein screenshot des Fehlers.
Interessant ist das auf einen Pfad verwiesen wird (siehe Bild grün - "C:\projects\linq2db...") der bei mir nicht existiert. Aber ich finde auch keinen Verweis darauf im gesamten Visual Projekt.
Vielleicht hast du eine idee wo der Fehler liegt und wie ich ihn beseitigen kann. Ich freue mich über jeden Tipp.
Danke und viele Grüße
Andreas

Problem during ReqIF export from MySQL Server Project.

![Error_EA_MySQL](https://user-images.githubusercontent.com/61977384/86047969-09a24180-ba50-11ea-8e25-41b6ed57c7ac.png)

**Comment by Helmut-Ortmann** [comment]
Hallo Andreas,

ich habe alles nur mit lokalem *.EAP file intensiv getestet.

Die error Message "MySql.Data" zeigt dass eine *.dll fehlt um auf die MySql
Datenbank zugreifen zu können. Du müsstest diese DLL und eventuelle
Abhängigkeiten im Build hinzufügen (files.wxs). Der ganze LINQ Zugriff ist
im Projekt hoLinqSql welches aus hoTools (
https://github.com/Helmut-Ortmann/EnterpriseArchitect_hoTools/wiki/hoTools?ref=umlchannel)
kommt gekapselt. Ist nicht perfekt gemacht.

Gerne kannst Du weiter Fragen oder wenn es ganz schwierig wird eine Skype
Session machen. Über Feedback oder Korrekturen freue ich mich. Ich würde
diese auch in eine neue Version integrieren. Da EA viele Datenbanken
unterstützt sind meine Möglichkeiten für Testen begrenzt.


Gruß,

Helmut
*  files.wxs  aus project hoReverse Setup *




*       <Component
Id="linq2db.dll" Guid="{7F7E0442-6625-451E-841E-E4D304EFBCBA}">
<File Id="linq2db.dll" KeyPath="yes" Name="linq2db.dll"
Source="$(var.NugetCollectorProject.TargetDir)\linq2db.dll" />
</Component>*



*       <Component
Id="MySql.Data.dll" Guid="{1D9AF997-5EFF-4F2A-9410-72EAA69473CC}">
<File Id="MySql.Data.dll" KeyPath="yes" Name="MySql.Data.dll"
Source="$(var.NugetCollectorProject.TargetDir)\MySql.Data.dll" />
</Component>*
      <Component Id="Microsoft.SqlServer.Types.dll"
Guid="{EABD70B2-374E-4959-AB91-38863D06ABFA}">
        <File Id="Microsoft.SqlServer.Types.dll" KeyPath="yes"
Name="Microsoft.SqlServer.Types.dll"
Source="$(var.NugetCollectorProject.TargetDir)\Microsoft.SqlServer.Types.dll"
/>
      </Component>
      <Component Id="Oracle.ManagedDataAccess.dll"
Guid="{1BE3E59F-3CA1-4725-8FB6-086E0DAD8D03}">
        <File Id="Oracle.ManagedDataAccess.dll" KeyPath="yes"
Name="Oracle.ManagedDataAccess.dll"
Source="$(var.NugetCollectorProject.TargetDir)\Oracle.ManagedDataAccess.dll"
/>
      </Component>
      <Component Id="Npgsql.dll"
Guid="{B63E7AC0-5F42-49A3-8ABD-4B84B8C9160D}">
        <File Id="Npgsql.dll" KeyPath="yes" Name="Npgsql.dll"
Source="$(var.NugetCollectorProject.TargetDir)\Npgsql.dll" />
      </Component>
      <Component Id="AdoNetCore.AseClient.dll"
Guid="{A3853976-5D6F-430E-AB0D-D87648B009D3}">
        <File Id="AdoNetCore.AseClient.dll" KeyPath="yes"
Name="AdoNetCore.AseClient.dll"
Source="$(var.NugetCollectorProject.TargetDir)\AdoNetCore.AseClient.dll" />
      </Component>
      <Component Id="Sybase.AdoNet.AseClient.dll"
Guid="{AF240101-8497-42E2-A2EE-7502385B7744}">
        <File Id="Sybase.AdoNet.AseClient.dll" KeyPath="yes"
Name="Sybase.AdoNet.AseClient.dll"
Source="$(var.NugetCollectorProject.TargetDir)\Sybase.AdoNet.AseClient.dll"
/>
      </Component>

**Comment by RobinTremec** [comment]
Hello Andreas,

I have came across that same issue. As explained by Helmut Ortmann, the .dlls are added to the installer using files.wxs.
If you are debugging or building from source, it might occur that some .dlls are not copied to the <projectroot>/hoReverseRoot/bin/Debug/ folder. You can do this manually once.

**Comment by AndreasW89** [comment]
> 
> 
> Hello Andreas,
> 
> I have came across that same issue. As explained by Helmut Ortmann, the .dlls are added to the installer using files.wxs.
> If you are debugging or building from source, it might occur that some .dlls are not copied to the /hoReverseRoot/bin/Debug/ folder. You can do this manually once.

Hi,
you are right. I was running the hoReverse tool as debug build. 
Now, I have build it as Release and installed it with the generate installation file. And finally it works on my MySQL projects.
I think I will not put any additional time to find the issue for the debug build. The release way is much better.
Thanks to you guys and best regards.
