### ISSUE TITLE
All user installer does not remove previous versions

### ISSUE THREAD

**Issue by RobinTremec** [Helmut-Ortmann/EnterpriseArchitect_hoReverse#9]
Due to the fact that the wix installer process checks for related products prior to the selection of all users vs single user, you get the following:
`FindRelatedProducts: current install is per-user.  Related install for product '{xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx}' is per-machine.  Skipping...`
And the per-machine install is not removed.
To fix, just add the next line in WixUI_Advanced.wxs (and WixUI_Advanced.wxs.default):
`<Publish Dialog="FeaturesDlg" Control="Install" Event="DoAction" Value="FindRelatedProducts">1</Publish>`

I chose to add this event to the "Install" button so any next/back actions do not break the functionality.

**Comment by Helmut-Ortmann** [comment]
Thanks a lot for your valuable issue. I'll include it.

**Comment by Helmut-Ortmann** [comment]
Fixed!

**Comment by GrahamRoach** [comment]
Thanks for your help Helmut
